backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "products"
    label: "Products"
    label_singular: "product" # Used in the UI, ie: "New Post"
    folder: "content/products"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown"}
  - name: "category"
    label: "Categories"
    label_singular: "category" # Used in the UI, ie: "New Post"
    folder: "content/categories"
    create: true
    fields:
      - { label: "title", name: "title", widget: "string"}
      - { label: "Publish date", name: "date", widget: "datetime" }


