backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "products"
    label: "Products"
    label_singular: "product" # Used in the UI, ie: "New Post"
    folder: "content/products"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "categories",
          value_field: "title",
          search_fields: ["title"],
        }
      - { label: "Year", name: "year", widget: "string" }
      - { label: "Manufacturer", name: "manufacturer", widget: "string" }
      - { label: "Model", name: "model", widget: "string" }
      - { label: "VIN", name: "vin", widget: "string" }
      - { label: "Condition", name: "condition", widget: "string" }
      - { label: "Stock Number", name: "stockNum", widget: "string" }
      - {
          label: "Engine Displacement",
          name: "engineDisplacement",
          widget: "string",
        }
      - { label: "Fuel Type", name: "fuel", widget: "string" }
      - { label: "Turbo", name: "turbo", widget: "string" }
      - { label: "transmission", name: "transmission", widget: "string" }
      - {
          label: "Steering Wheel Location",
          name: "steeringWheel",
          widget: "string",
        }

  - name: "categories"
    label: "Categories"
    label_singular: "category" # Used in the UI, ie: "New Post"
    folder: "content/categories"
    create: true
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "Publish date", name: "date", widget: "datetime" }
